### ISSUE TITLE
How is this coming along?

### ISSUE THREAD

**Issue by niels-hubs** [PsychoMnts/Xiaomi-Scooter-Motion-Control#2]
Hi Glenn,

I am really interested in helping out with your project. I got a few idea's on how to improve the code. Have you tested it on a Xiaomi e-step yet and tested that you can successfully manipulate the serial-bus?

**Comment by PsychoMnts** [comment]
Hi Niels,

Yes, I purchased a test scooter last week (Xiaomi Scooter Essential). I have done some interesting discovery's:
- The throttle wire doesn't like PWM. I was able to fix that with an RC-filter. So yes, I can control the throttle now!
I will update the schematics soon.
- The serial bus is conflicting with the USB->Serial chip on the Arduino. So that means that the Arduino Nano won't work. I'm currently using an Arduino Mega, because it has multiple serial connections available which makes debugging easier.
- The scooters with an 2 digit display are using different firmware and I was not able to get the speed from the ESC. I spent today decoding the serial bus to find the value. The sad thing is that it now only has 2 digits, but I can read it now.

For this project the code is actually unnessary complex, we only need 3 things:
- The speed value
- The value of the brake handle
- Throttle control (0.85v = 0%, 4.15v = 100%) 
It is not need to be able to send on the serial-bus

I have created an telegram group for development, you can join if you like:
https://t.me/joinchat/Sm-3PGOpWv-WlB7E

**Comment by niels-hubs** [comment]
Great to hear! My equipment will arrive next week so I can start helping out. I've joined the Telegram group as well, however I can't send messages yet. Speak to you in Telegram soon!
